// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_vY7mHVWhZ7z9FhgFim3mCItJ2rp7SA',
    appId: '1:870779474061:web:f8eddd467c998e26e3d2c4',
    messagingSenderId: '870779474061',
    projectId: 'nota-16dd9',
    authDomain: 'nota-16dd9.firebaseapp.com',
    storageBucket: 'nota-16dd9.firebasestorage.app',
    measurementId: 'G-6024WNT682',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9559J7QdGMtLcz5cIulvf2fVrxla8Oc0',
    appId: '1:870779474061:android:1b7eeb3366ca3199e3d2c4',
    messagingSenderId: '870779474061',
    projectId: 'nota-16dd9',
    storageBucket: 'nota-16dd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC08QpfPLFjJaYncZ4boJuzMEXserNVl10',
    appId: '1:870779474061:ios:13779bec84156502e3d2c4',
    messagingSenderId: '870779474061',
    projectId: 'nota-16dd9',
    storageBucket: 'nota-16dd9.firebasestorage.app',
    iosBundleId: 'com.example.nota',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC08QpfPLFjJaYncZ4boJuzMEXserNVl10',
    appId: '1:870779474061:ios:13779bec84156502e3d2c4',
    messagingSenderId: '870779474061',
    projectId: 'nota-16dd9',
    storageBucket: 'nota-16dd9.firebasestorage.app',
    iosBundleId: 'com.example.nota',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS_vY7mHVWhZ7z9FhgFim3mCItJ2rp7SA',
    appId: '1:870779474061:web:587a356375ede474e3d2c4',
    messagingSenderId: '870779474061',
    projectId: 'nota-16dd9',
    authDomain: 'nota-16dd9.firebaseapp.com',
    storageBucket: 'nota-16dd9.firebasestorage.app',
    measurementId: 'G-L4MDD6MVQQ',
  );
}
